services:
  backend:
    container_name: management-backend
    build:
      context: ./management
    ports:
      - "8081:8080"   # HOST:CONTAINER
    restart: always

  frontend:
    container_name: salesmanagement-frontend
    build:
      context: ./salesmanagement
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

