version: "3.9"

services:
  backend:
    container_name: management-backend
    build:
      context: ./management
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./management/.env

  frontend:
    container_name: salesmanagement-frontend
    build:
      context: ./salesmanagement
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: always

