services:
  backend:
    container_name: management-backend
    build:
      context: ./management
    ports:
      - "8081:8080"     # HOST:CONTAINER
    restart: always

  frontend:
    container_name: salesmanagement-frontend
    build:
      context: ./salesmanagement
    ports:
      - "8082:80"       # HOST:CONTAINER
    depends_on:
      - backend
    restart: always

