services:
  backend:
    build: ./management
    container_name: management-backend
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./salesmanagement
    container_name: salesmanagement-frontend
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: always

