services:
  backend:
    container_name: management-backend
    build:
      context: ./management
    ports:
      - "8080:8080"
    restart: always

  frontend:
    container_name: salesmanagement-frontend
    build:
      context: ./salesmanagement
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: always

